// ============ HEAVY CIVIL & MARINE ============
var HEAVY_CATEGORIES={
"Dredging & Reclamation":["Hydraulic dredging - cutter suction","Hydraulic dredging - trailing suction hopper","Mechanical dredging - backhoe","Mechanical dredging - grab","Mechanical dredging - bucket ladder","Dredged material disposal - offshore","Dredged material disposal - confined","Dredged material disposal - beneficial reuse","Land reclamation - sand fill","Land reclamation - hydraulic fill","Shore protection during reclamation","Silt curtain/turbidity barrier","Bathymetric survey pre-dredge","Bathymetric survey post-dredge","Dredge depth monitoring","Environmental monitoring - water quality","Environmental monitoring - marine life","Navigation channel maintenance dredging","Berth pocket dredging","Turning basin dredging"],
"Railways - Track Works":["Rail formation/subgrade preparation","Sub-ballast layer 150mm","Ballast layer 300mm - granite","Ballast compaction & profiling","Rail - UIC 60 (60kg/m)","Rail - UIC 54 (54kg/m)","Rail - 50kg/m","Rail welding - aluminothermic","Rail welding - flash butt","Rail expansion joints","Concrete sleepers - pre-tensioned","Concrete sleepers - post-tensioned","Steel sleepers","Timber sleepers - treated","Sleeper spacing 600mm","Rail fastening - Pandrol clip","Rail fastening - bolted","Turnout/switch installation","Crossing/frog installation","Check rail installation","Guard rail installation","Buffer stop installation","Rail lubrication system","Rail grinding","Track alignment - tamping","Track alignment - lining","Track leveling","Ballast regulating","Dynamic track stabilisation"],
"Railways - Stations & Platforms":["Station platform - precast","Station platform - in-situ concrete","Platform copings","Platform edge warning tiles","Platform height 1100mm above rail","Station building - steel frame","Station building - concrete","Station canopy/roof","Footbridge - steel","Footbridge - concrete","Subway/underpass","Ticket office/booth","Waiting room/shelter","Platform seating","Platform lighting","Platform signage","PA system installation","CCTV for station","Departure board/display","Fencing along track","Level crossing - manned","Level crossing - unmanned","Level crossing - barriers & lights"],
"Railways - Signaling & OHE":["Signal - colour light LED","Signal - position light","Signal gantry/structure","Track circuit installation","Axle counter installation","Point machine - electric","Point machine - hydraulic","Interlocking system - relay","Interlocking system - electronic","Train detection system","Signaling cable - armoured","Signaling cable termination","Signal power supply","OHE mast - steel lattice","OHE mast - tubular","OHE portal structure","OHE cantilever assembly","Contact wire - copper","Catenary wire - bronze","Dropper installation","Section insulator","Tensioning device - auto","Tensioning device - manual","Neutral section","Earthing & bonding - OHE"],
"Dams & Reservoirs":["Dam site investigation - geology","Dam foundation excavation","Dam foundation - grout curtain","Dam foundation - dental concrete","Embankment dam - earth fill","Embankment dam - rock fill","Embankment dam - clay core","Embankment dam - filter/drain zones","Embankment dam - riprap protection","Concrete gravity dam - mass concrete","Concrete gravity dam - RCC (Roller Compacted)","Concrete arch dam","Dam spillway - ogee crest","Dam spillway - chute","Dam spillway - stilling basin","Dam spillway - radial gates","Dam spillway - flap gates","Dam outlet works - intake tower","Dam outlet works - conduit/pipe","Dam outlet works - control valve","Dam outlet works - scour valve","Dam instrumentation - piezometers","Dam instrumentation - settlement markers","Dam instrumentation - weir/V-notch","Dam instrumentation - seismograph","Reservoir clearing - vegetation","Reservoir clearing - structures","Reservoir impoundment plan","Dam safety inspection","Dam maintenance access road"],
"Waterfront Structures - Quay Walls":["Quay wall - sheet pile","Quay wall - combi-wall","Quay wall - diaphragm wall","Quay wall - concrete caisson","Quay wall - block wall","Quay wall - relieving platform","Quay wall - tied anchor wall","Quay wall - deadman anchors","Quay wall - ground anchors","Quay wall - cope beam","Quay wall - capping beam","Fender - rubber cone","Fender - rubber cell","Fender - timber","Bollard - 50T","Bollard - 100T","Bollard - 150T","Mooring ring","Ladder - access","Crane rail - quay","Crane rail - grouted","Crane rail - continuous pad","Quay drainage system","Quay backfill - dredged","Quay backfill - imported","Scour protection at toe"],
"Waterfront Structures - Jetties & Piers":["Jetty - piled concrete deck","Jetty - steel pipe piles","Jetty - concrete piles","Jetty - timber piles","Jetty - precast deck panels","Jetty - in-situ deck","Jetty - access trestle","Jetty - mooring dolphin","Jetty - berthing dolphin","Jetty - breasting dolphin","Jetty - walkway/platform","Jetty - handrailing","Jetty - fendering system","Jetty - bollards","Jetty - navigation lights","Pier - solid construction","Pier - open piled","Finger pier - floating","Finger pier - fixed","Pontoon - concrete","Pontoon - steel","Pontoon - timber","Gangway - aluminium","Gangway - steel"],
"Waterfront Structures - Breakwaters":["Breakwater - rubble mound","Breakwater - concrete caisson","Breakwater - tetrapod armour","Breakwater - dolos armour","Breakwater - accropode armour","Breakwater - core material","Breakwater - filter layers","Breakwater - underlayer","Breakwater - toe berm","Breakwater - crown wall","Breakwater - wave wall","Breakwater - head/roundhead","Groynes - timber","Groynes - rock","Groynes - concrete","Revetment - stone pitching","Revetment - concrete blocks","Revetment - gabion mattress","Seawall - concrete stepped","Seawall - recurved","Seawall - sheet pile"],
"Tunnels & Tunneling":["Tunnel - cut & cover","Tunnel - bored (TBM)","Tunnel - drill & blast","Tunnel - NATM (New Austrian)","Tunnel - immersed tube","Tunnel - micro-tunneling","Tunnel - pipe jacking","Tunnel - shaft construction","Tunnel - portal construction","Tunnel - initial/primary lining","Tunnel - shotcrete application","Tunnel - rock bolts","Tunnel - steel ribs/arches","Tunnel - lattice girders","Tunnel - secondary/final lining","Tunnel - waterproofing membrane","Tunnel - geotextile protection","Tunnel - concrete lining - cast in place","Tunnel - concrete lining - precast segments","Tunnel - invert concrete","Tunnel - drainage system","Tunnel - ventilation system","Tunnel - jet fans","Tunnel - axial fans","Tunnel - lighting system","Tunnel - emergency lighting","Tunnel - fire fighting system","Tunnel - deluge system","Tunnel - emergency exits","Tunnel - cross passages","Tunnel - communication system","Tunnel - CCTV monitoring","Tunnel - SCADA/control system","Tunnel - air quality monitoring","Tunnel - settlement monitoring","Tunnel - convergence monitoring","Tunnel - ground treatment/grouting","Tunnel - freeze ground (temporary)","Tunnel - compressed air working","Tunnel - muck handling/conveyor","Tunnel - segment factory","Tunnel - TBM assembly chamber","Tunnel - TBM retrieval shaft"],
"Underwater Works":["Underwater inspection - diver","Underwater inspection - ROV","Underwater concrete placement - tremie","Underwater concrete - anti-washout","Underwater welding","Underwater cutting","Underwater bolting/grouting","Underwater formwork","Underwater pile driving","Underwater rock excavation","Underwater blasting","Cofferdam - sheet pile","Cofferdam - earth/rock","Cofferdam - cellular","Caisson - open","Caisson - pneumatic","Caisson - box","Caisson sinking","Underwater pipeline installation","Submarine cable installation","Outfall construction","Intake structure construction"],
"Intake Structures":["River intake screened","River intake submerged","Lake/reservoir intake multi-level","Intake screen coarse bar","Intake screen fine bar","Intake screen travelling band","Intake trash rack","Intake gate/penstock","Intake fish screen","Intake flow meter","Intake level sensor","Intake scour/silt flush","Intake desilting basin"],
"Water Treatment Works":["Raw water inlet chamber","Coagulation/flash mixing","Flocculation tank","Sedimentation tank","Filtration rapid sand","Filtration pressure filter","Filtration activated carbon","Filtration membrane/ultrafiltration","Filtration reverse osmosis","Disinfection chlorine dosing","Disinfection ozone","Disinfection UV treatment","Clear water tank","Treated water pumping station","Chemical storage & dosing","Sludge thickening","Sludge drying beds","Sludge dewatering","Backwash water recovery","Treated water quality lab","Treated water flow meter","Treated water reservoir"],
"Wells & Boreholes":["Hydrogeological survey","Test drilling/borehole","Borehole rotary drilling","Borehole DTH hammer","Borehole casing steel/PVC","Borehole screen slotted","Borehole gravel pack","Borehole grout seal","Borehole sanitary seal","Borehole development air lift","Borehole yield test","Borehole water quality test","Borehole pump submersible","Borehole pump hand pump","Borehole pump solar","Borehole rising main","Borehole headworks/chamber","Borehole flow meter","Borehole level indicator","Borehole chlorination","Borehole completion report","Dug well concrete rings","Dug well cover slab","Dug well apron & drainage"],
"Discharge & Regulating Structures":["Sluice gate cast iron","Sluice gate electric actuated","Penstock weir type","Penstock orifice type","Stop logs aluminium","Butterfly valve","Gate valve resilient seated","Non-return/check valve","Pressure reducing valve","Flow control valve","Float valve","Air release valve","Surge protection air vessel","Surge protection surge tank","Flow meter electromagnetic","Flow meter ultrasonic","Level sensor ultrasonic","Level sensor radar","Discharge channel concrete lined","Discharge channel riprap","Discharge channel stilling basin","Discharge channel energy dissipator","Discharge channel scour protection"]
};
var HEAVY_STATUS=["Not started","Mobilized","In progress","Partially complete","Structurally complete","Finishing","Inspected","Commissioned","Completed"];

RENDER["heavy"]=function(){
var h='<h2>Heavy Civil & Marine Works</h2><p style="color:#aaa;font-size:12px">Dredging, Railways, Dams, Waterfront, Tunnels</p>';
h+='<div style="display:flex;gap:8px;margin:10px 0"><button class="btn btn-blue btn-sm" onclick="showHeavyForm()">+ Add Item</button></div>';
var hv=(D.heavy||[]);
if(hv.length===0){h+='<p style="color:#666">No heavy civil items recorded.</p>';}
else{
var cats={};for(var i=0;i<hv.length;i++){var it=hv[i];if(!cats[it.category])cats[it.category]=[];cats[it.category].push(it);}
var ck=Object.keys(cats);
for(var c=0;c<ck.length;c++){var cat=ck[c];var items=cats[cat];
h+='<div class="card"><h4>'+cat+' ('+items.length+')</h4><table style="font-size:10px"><tr><th>Item</th><th>Location</th><th>Qty</th><th>Status</th><th></th></tr>';
for(var i=0;i<items.length;i++){var it=items[i];h+='<tr><td>'+it.name+'</td><td>'+it.location+'</td><td>'+it.qty+' '+it.unit+'</td><td><span class="tag '+(it.status==="Completed"||it.status==="Commissioned"?"tag-pass":"tag-open")+'">'+it.status+'</span></td><td><button class="btn btn-red btn-sm" style="padding:2px 6px;font-size:10px" onclick="delItem(\'heavy\',\''+it.id+'\');go(\'heavy\')">X</button></td></tr>';}
h+='</table></div>';}
}
return h;
};
function showHeavyForm(){
var cats="";var ck=Object.keys(HEAVY_CATEGORIES);for(var i=0;i<ck.length;i++){cats+='<option value="'+ck[i]+'">'+ck[i]+'</option>';}
var h='<h3>Add Heavy Civil Item</h3><label>Date:</label><input type="date" id="_entryDate" value="'+globalDate+'" max="'+today()+'"><label>Category:</label><select id="_hvCat" onchange="loadHVItems()">'+cats+'</select><label>Item:</label><select id="_hvItem"></select><label>Location:</label><input id="_hvLoc" placeholder="e.g. Ch 0+500, Berth 3"><div class="row"><div><label>Quantity:</label><input id="_hvQty" type="number" value="1"></div><div><label>Unit:</label><select id="_hvUnit"><option>m</option><option>m2</option><option>m3</option><option>km</option><option>Pieces</option><option>Sets</option><option>Tons</option></select></div></div><label>Status:</label><select id="_hvStatus">';
for(var i=0;i<HEAVY_STATUS.length;i++){h+='<option>'+HEAVY_STATUS[i]+'</option>';}
h+='</select><label>Notes:</label><input id="_hvNotes"><button class="btn" onclick="saveHeavy()">Save</button><button class="btn btn-secondary" onclick="go(\'heavy\')">Cancel</button>';
document.getElementById("content").innerHTML=h;loadHVItems();
}
function loadHVItems(){var cat=document.getElementById("_hvCat").value;var items=HEAVY_CATEGORIES[cat]||[];var h="";for(var i=0;i<items.length;i++){h+='<option>'+items[i]+'</option>';}document.getElementById("_hvItem").innerHTML=h;}
function saveHeavy(){if(!D.heavy)D.heavy=[];D.heavy.push({id:uid(),date:document.getElementById("_entryDate").value,category:document.getElementById("_hvCat").value,name:document.getElementById("_hvItem").value,location:document.getElementById("_hvLoc").value,qty:document.getElementById("_hvQty").value,unit:document.getElementById("_hvUnit").value,status:document.getElementById("_hvStatus").value,notes:document.getElementById("_hvNotes").value,timestamp:Date.now()});save();toast("Saved!");go("heavy");}
