var PHASE_INSPECTIONS={
"45. Formwork - Foundations":["Setting out checked against grid","Excavation sides vertical and stable","Blinding level ±10mm","Blinding compacted and cured","Kicker height 100-150mm from blinding","Kicker formwork plumb","Kicker formwork braced","Pad footing formwork square","Pad footing dimensions ±10mm","Strip footing formwork aligned","Strip footing width correct","Strip footing depth correct","Raft edge formwork level","Raft edge formwork braced","Ground beam formwork level","Ground beam sides plumb","Ground beam width correct","Formwork joints sealed no grout loss","Mould oil applied","Formwork clean before use","Formwork braces both directions","Formwork checked by engineer before pour","Stop ends at construction joints","Pocket/insert positions correct","Formwork release agent applied","Formwork stripped after 24-48hrs for sides","Formwork stripped after 7 days for soffits"],
"46. Formwork - Columns":["Column position from grid ±5mm","Column dimensions ±5mm","Column formwork plumb checked with spirit level","Column formwork plumb both directions","Column formwork braced at 45 degrees","Column formwork joints sealed","Column kicker formed and cured","Kicker dimensions match column","Kicker level","Column box square checked","Column box diagonals equal","Column formwork oiled","Column formwork clean","Column clamps at correct spacing","Column ties at 450mm c/c","Column wedges tight","Column formwork checked before pour","Column pour height marked","Column formwork not struck before 48hrs","Column formwork stripped carefully","Column formwork cleaned after use","Column formwork repaired if damaged"],
"47. Formwork - Beams":["Beam position from grid ±5mm","Beam soffit level ±5mm","Beam soffit props vertical","Beam soffit props at 1.2m c/c max","Beam soffit props braced","Beam side shutters plumb","Beam width ±5mm","Beam depth ±5mm","Beam side shutters braced","Beam formwork joints sealed","Beam mould oil applied","Beam formwork clean","Beam clamps at 600mm c/c","Beam ties if required","Beam formwork checked before pour","Beam pour level marked","Beam formwork not struck before 14 days","Beam soffit props left in place","Beam formwork stripped carefully","Beam formwork cleaned after use"],
"48. Formwork - Slabs":["Slab soffit level ±5mm checked with laser","Slab soffit props vertical","Slab soffit props at 1.2m c/c","Slab soffit props braced both directions","Slab main bearers level","Slab secondary joists at 600mm c/c","Slab plywood 18mm minimum","Slab plywood joints tight","Slab edge formwork level","Slab edge formwork braced","Slab edge formwork height = slab thickness","Slab openings boxed out","Slab openings correctly positioned","Slab upstand formwork if any","Slab downstand beam formwork","Slab formwork joints sealed","Slab mould oil applied","Slab formwork clean","Slab formwork camber for spans >6m","Slab formwork checked before pour","Slab formwork not struck before 14 days","Slab backpropping installed","Slab formwork struck carefully","Slab formwork cleaned and stacked"],
"49. Formwork - Stairs":["Stair position from grid ±5mm","Stair waist soffit level","Stair waist props at 1m c/c","Stair side shutters plumb","Riser height uniform ±3mm","Tread width uniform ±3mm","Riser boards 25mm timber","Riser boards braced","Riser boards vertical","Tread boards if required","Stair formwork joints sealed","Stair mould oil applied","Stair formwork clean","Stair landing formwork level","Stair landing props independent","Stair formwork checked before pour","Stair formwork not struck before 21 days","Stair props left in place","Stair formwork stripped carefully"],
"50. Reinforcement - Foundations":["Bar schedule checked against drawings","Bar sizes correct","Bar spacing ±10mm","Bar cover blocks 50mm to earth","Bar cover blocks 40mm to blinding","Bar laps correct length","Bar laps staggered","Bar tying correct","Bar clean no mud/rust","Bar chairs for top mat","Bar starter bars correct position","Starter bars correct length above kicker","Starter bars protected from damage","Bar tags match schedule","BBS as-built submitted"],
"51. Reinforcement - Columns":["Bar sizes correct","Number of bars correct","Bar spacing checked","Stirrup/links spacing at supports","Stirrup/links spacing at midspan","Stirrup hooks 135 degrees","Stirrup size correct","Cover blocks 25mm minimum","Cover blocks at 1m c/c","Lap length 45d for tension","Laps staggered","Bars tied securely","Bars clean","Starter bars from foundation aligned","Dowel bars into next column","Column cage plumb","Cage dimensions match column"],
"52. Reinforcement - Beams":["Bottom bars size correct","Bottom bars number correct","Top bars size correct","Top bars number correct","Stirrup size correct","Stirrup spacing at supports","Stirrup spacing at midspan","Stirrup hooks 135 degrees","Extra top bars at supports","Side face bars if beam >450mm","Cover blocks 40mm bottom","Cover blocks 25mm sides","Laps at supports not midspan","Laps staggered","Bars tied securely","Bars clean","Cranked bars correct","Curtailment as per drawing"],
"53. Reinforcement - Slabs":["Bottom bars main span correct","Bottom bars distribution correct","Bar spacing ±10mm","Top bars at supports correct","Extra top bars at midspan if required","Mesh size correct (A142/A193/A252)","Mesh laps 300mm minimum","Mesh chaired 25mm minimum","Chairs at 600mm c/c","Cover blocks 20mm minimum","Laps staggered","Bars tied every intersection","Bars clean","Trim bars around openings correct","Slab thickening at edges if required","BBS as-built submitted"],
"54. Reinforcement - Stairs":["Waist bottom bars correct","Waist distribution bars correct","Waist top bars at supports","Landing bottom bars correct","Landing top bars correct","Landing continuity bars","Starter bars from beam","Dowel bars into wall","Cover blocks 20mm minimum","Chairs for top bars","Bar laps correct","Bars tied securely","Bars clean","Cranked bars at landing junction correct"]
};
