var PLANT_INSTALL={
"Tower Crane":["Crane position survey - within tolerance","Crane foundation design approved","Foundation excavation - depth correct","Foundation reinforcement - as per design","Foundation anchor bolts - correctly positioned","Foundation anchor bolts - template used","Foundation concrete - C30/37 min","Foundation concrete - cured 7 days min","Foundation level - within ±3mm","Anchor bolt projection - correct","Crane delivery - components inspected","Crane base section - installed on anchors","Crane base section - leveled with shims","Crane base section - grouted","Crane mast sections - erected in sequence","Crane mast - bolted torque checked","Crane ties to building - installed at 3 floor intervals","Crane ties - properly anchored","Crane jib - assembled on ground","Crane jib - lifted and connected","Crane counter jib - installed","Crane counterweights - installed as per load chart","Crane trolley - installed","Crane hook block - installed","Crane climbing frame - installed","Crane climb - hydraulic system","Crane climb - sequence per manual","Crane slewing ring - greased","Crane hoist ropes - correctly reeved","Crane hoist ropes - no kinks or damage","Crane limit switches - set correctly","Crane load moment indicator - calibrated","Crane anemometer - installed","Crane anti-collision system - if multiple cranes","Crane lighting - aviation warning light","Crane earthing - connected","Crane testing - overload test 125%","Crane testing - all motions","Crane testing - emergency stop","Crane inspection - by competent person","Crane inspection - statutory certificate","Crane handover - to operator","Crane maintenance - log book started"],
"Passenger/Material Hoist":["Hoist position - survey","Hoist foundation - concrete pad","Hoist foundation - level","Hoist mast sections - erected","Hoist mast - bolted","Hoist ties to building - every 3 floors","Hoist ties - secure","Hoist cage - installed","Hoist cage - doors work","Hoist landing gates - at each floor","Hoist landing gates - self-closing","Hoist motor - installed","Hoist brake - tested","Hoist limit switches - set","Hoist overload sensor - calibrated","Hoist intercom - between floors","Hoist earthing - connected","Hoist testing - full load","Hoist testing - emergency stop","Hoist inspection - competent person","Hoist certificate - issued","Hoist handover - to operator"],
"Concrete Batching Plant":["Plant position - survey","Plant foundation - concrete slab","Plant foundation - level","Aggregate bins - installed","Aggregate bins - separated","Cement silo - installed","Cement silo - foundation","Cement silo - level","Conveyor - from bins to mixer","Conveyor - aligned","Mixer - installed","Mixer - capacity check","Water tank - installed","Water meter - calibrated","Additive tank - installed","Control cabin - installed","Control panel - programmed","Control panel - mix designs input","Weighing system - calibrated","Weighing system - accuracy ±2%","Dust collection - installed","Dust collection - working","Plant earthing - connected","Plant testing - trial mix","Plant testing - output capacity","Plant inspection - issued","Plant handover - to operator"],
"Generator - Site Power":["Generator position - survey","Generator foundation - concrete pad","Generator foundation - level","Generator - placed on foundation","Generator - bolted down","Generator - anti-vibration mounts","Fuel tank - installed","Fuel tank - bunded","Fuel tank - capacity check","Fuel lines - connected","Fuel lines - no leaks","Exhaust - silencer installed","Exhaust - directed away from work areas","Generator - wiring to DB","Generator - earthing","Generator - auto transfer switch","Generator - synchronisation (if multiple)","Generator - load test","Generator - all circuits powered","Generator - fuel consumption check","Generator - noise level check","Generator - inspection certificate","Generator - handover log"],
"Concrete Pump - Stationary":["Pump position - survey","Pump - on stable ground","Pump - outriggers extended","Pump - outriggers on pads","Boom - unfolded per manual","Boom - clear of overhead lines","Boom - clear of structures","Pipeline - from pump to pour area","Pipeline - supported","Pipeline - clamps tight","Pipeline - bends as per radius","Pipeline - no leaks","Pipeline - cleaned after pour","Pump - hopper screen","Pump - safety grilles","Pump - emergency stop tested","Pump - inspection done","Pump - handover to operator"]
};
var PLANT_INSTALL_STATUS=["Not started","Foundation","Installation","Testing","Certified","Handed over"];
RENDER["plantinstall"]=function(){
var h='<h2>Plant Installation</h2><p style="color:#aaa;font-size:12px">Cranes, Hoists, Batching Plants, Generators before construction</p>';
h+='<div style="display:flex;gap:8px;margin:10px 0"><button class="btn btn-blue btn-sm" onclick="showPlantInstallForm()">+ Add Item</button></div>';
var pi=(D.plantinstall||[]);
if(pi.length===0){h+='<p style="color:#666">No plant installation items recorded.</p>';}
else{
var cats={};for(var i=0;i<pi.length;i++){var it=pi[i];if(!cats[it.category])cats[it.category]=[];cats[it.category].push(it);}
var ck=Object.keys(cats);
for(var c=0;c<ck.length;c++){var cat=ck[c];var items=cats[cat];
h+='<div class="card"><h4>'+cat+' ('+items.length+')</h4><table style="font-size:10px"><tr><th>Item</th><th>Location</th><th>Qty</th><th>Status</th><th></th></tr>';
for(var i=0;i<items.length;i++){var it=items[i];h+='<tr><td>'+it.name+'</td><td>'+it.location+'</td><td>'+it.qty+' '+it.unit+'</td><td><span class="tag '+(it.status==="Handed over"||it.status==="Certified"?"tag-pass":"tag-open")+'">'+it.status+'</span></td><td><button class="btn btn-red btn-sm" style="padding:2px 6px;font-size:10px" onclick="delItem(\'plantinstall\',\''+it.id+'\');go(\'plantinstall\')">X</button></td></tr>';}
h+='</table></div>';}
}
return h;
};
function showPlantInstallForm(){
var cats="";var ck=Object.keys(PLANT_INSTALL);for(var i=0;i<ck.length;i++){cats+='<option value="'+ck[i]+'">'+ck[i]+'</option>';}
var h='<h3>Add Plant Installation Item</h3><label>Date:</label><input type="date" id="_entryDate" value="'+globalDate+'" max="'+today()+'"><label>Plant Type:</label><select id="_piCat" onchange="loadPiItems()">'+cats+'</select><label>Item:</label><select id="_piItem"></select><label>Location:</label><input id="_piLoc"><div class="row"><div><label>Quantity:</label><input id="_piQty" type="number" value="1"></div><div><label>Unit:</label><select id="_piUnit"><option>Pieces</option><option>Sets</option><option>m</option><option>m2</option></select></div></div><label>Status:</label><select id="_piStatus">';
for(var i=0;i<PLANT_INSTALL_STATUS.length;i++){h+='<option>'+PLANT_INSTALL_STATUS[i]+'</option>';}
h+='</select><label>Notes:</label><input id="_piNotes"><button class="btn" onclick="savePlantInstall()">Save</button><button class="btn btn-secondary" onclick="go(\'plantinstall\')">Cancel</button>';
document.getElementById("content").innerHTML=h;loadPiItems();
}
function loadPiItems(){var cat=document.getElementById("_piCat").value;var items=PLANT_INSTALL[cat]||[];var h="";for(var i=0;i<items.length;i++){h+='<option>'+items[i]+'</option>';}document.getElementById("_piItem").innerHTML=h;}
function savePlantInstall(){if(!D.plantinstall)D.plantinstall=[];var d=document.getElementById("_entryDate").value;var name=document.getElementById("_piItem").value;var loc=document.getElementById("_piLoc").value;D.plantinstall.push({id:uid(),date:d,category:document.getElementById("_piCat").value,name:name,location:loc,qty:document.getElementById("_piQty").value,unit:document.getElementById("_piUnit").value,status:document.getElementById("_piStatus").value,notes:document.getElementById("_piNotes").value,timestamp:Date.now()});save();toast("Saved!");go("plantinstall");}
