// ============ ROOFS & ROOF COVERINGS (COMPLETE) ============
var ROOF_CATEGORIES={
"Roof Structure - Timber":["Timber trusses - Pine treated (span 6m)","Timber trusses - Pine treated (span 9m)","Timber trusses - Pine treated (span 12m)","Timber trusses - Hardwood (span 6m)","Timber trusses - Hardwood (span 9m)","Timber rafters 100x50mm","Timber rafters 150x50mm","Timber purlins 100x50mm","Timber purlins 150x50mm","Timber purlins 200x50mm","Wall plate 100x50mm","Wall plate 150x50mm","Tie beam 150x50mm","Collar tie 100x50mm","Struts/braces 100x50mm","Hangers 100x50mm","Brandering 50x25mm","Counter battens 50x25mm","T&G boards 25x150mm (roof deck)","T&G boards 25x100mm","T&G boards 19x100mm (soffit)","Blockboard 18mm (flat roof deck)"],
"Roof Structure - Steel":["Steel trusses - Angle iron 50x50x6","Steel trusses - Angle iron 75x75x8","Steel trusses - Tubular 50mm","Steel trusses - Tubular 75mm","Steel trusses - Tubular 100mm","Steel purlins - C channel 100x50","Steel purlins - C channel 150x65","Steel purlins - C channel 200x75","Steel purlins - Z channel 150x65","Steel purlins - Z channel 200x75","Steel rafters - I-beam","Steel wall plate - Channel","Steel tie rod 12mm","Steel tie rod 16mm","Steel cleats/brackets","Base plate 200x200x10mm","Anchor bolts M16","Anchor bolts M20"],
"Roof Coverings - Metal Sheets":["Iron sheets G30 2.0m (28ga)","Iron sheets G30 2.5m","Iron sheets G30 3.0m","Iron sheets G30 3.5m","Iron sheets G28 2.5m (26ga)","Iron sheets G28 3.0m","Iron sheets G28 3.5m","Iron sheets G32 2.5m (24ga)","Aluminium sheets 2.5m","Aluminium sheets 3.0m","Box profile sheets 0.5mm","Box profile sheets 0.6mm","Corrugated sheets standard","Corrugated sheets heavy gauge","Pre-painted sheets (Colour coated)","Stone coated steel tiles","Mabati (Standard corrugated iron)","Mabati (Heavy gauge)"],
"Roof Coverings - Tiles":["Concrete tiles - Double Roman","Concrete tiles - Single Roman","Concrete tiles - Flat interlocking","Concrete tiles - Bold roll","Clay tiles - Double Roman","Clay tiles - Single Roman","Clay tiles - Flat","Clay tiles - Half round","Mangalore tiles (Indian)","Decra/Decramastic tiles","Slate tiles - Natural","Slate tiles - Fibre cement","Solar roof tiles","Terracotta tiles","Italian tiles"],
"Hidden/Concealed Roof Systems":["Standing seam (concealed clip)","Hidden fastener profile sheets","Interlocking aluminium panels","Snap-lock standing seam","Crimped standing seam","Flat lock panels","Composite panels (sandwich)","Built-up roofing (BUR)","Single-ply membrane (PVC)","Single-ply membrane (TPO)","Liquid applied membrane","Torch-on membrane 3mm","Torch-on membrane 4mm","Self-adhesive membrane","Green roof system","Concrete slab roof","Concrete flat roof with screed"],
"Ridge, Hips & Valleys":["Ridge cap - Iron 2.0m","Ridge cap - Galvanized 2.0m","Ridge cap - Aluminium","Ridge cap - Coloured","Ridge cap - Tile (concrete)","Ridge cap - Tile (clay)","Hip cap - Iron","Hip cap - Tile","Valley gutter - Iron","Valley gutter - Aluminium","Valley gutter - Lead","Valley board - Timber","Ridge seal/foam","Ridge screws with washers","Ridge ventilator","Hip iron/strap","Monoridge (ventilated ridge)"],
"Verges, Eaves & Edges":["Verge board - timber 6x1 (150x25mm)","Verge board - timber 8x1 (200x25mm)","Verge board - UPVC white","Verge board - UPVC woodgrain","Barge board - timber 6x1","Barge board - UPVC","Fascia board 6x1 (150x25mm)","Fascia board 8x1 (200x25mm)","Fascia board - UPVC 150mm","Fascia board - UPVC 200mm","Fascia board - UPVC 300mm","Soffit board - T&G timber","Soffit board - UPVC 300mm","Soffit board - UPVC 400mm","Soffit board - cement board","Eaves filler/comb (corrugated)","Eaves filler (box profile)","Verge clip/bracket","Soffit vent - circular","Soffit vent - strip","Over fascia vent","Bird comb/verge strip","Drip edge/flashing","Eaves angle trim","Fascia bracket","Fascia joint cover"],
"Roof Drainage":["Gutter UPVC 100mm x 3m (Half round)","Gutter UPVC 150mm x 3m","Gutter UPVC 100mm x 3m (Square)","Gutter UPVC 150mm x 3m (Square)","Gutter - Aluminium 125mm","Gutter - Galvanized 100mm","Gutter - Galvanized 150mm","Gutter - Box/parapet","Downpipe UPVC 100mm x 3m (Round)","Downpipe UPVC 100mm x 3m (Square)","Downpipe UPVC 150mm x 3m","Downpipe - Aluminium 100mm","Rainwater head/hopper","Shoe/Offset bend 100mm","Shoe/Offset bend 150mm","Gutter bracket - Fascia mount","Gutter bracket - Rafter mount","Downpipe clip/strap","Downpipe connector","Gutter union/connector","Stop end - Left","Stop end - Right","Gutter angle 90deg","Gutter angle 135deg","Leaf guard/gutter mesh","First flush diverter","Rainwater filter","Rain chain (decorative downpipe)"],
"Roof Insulation & Underlay":["Sisalation/Underlay - Single foil","Sisalation/Underlay - Double foil","Breathable membrane - Roofshield","Vapour barrier - Polyethylene","Glass wool insulation 50mm","Glass wool insulation 100mm","Rock wool insulation 50mm","Rock wool insulation 100mm","Polystyrene board 25mm","Polystyrene board 50mm","Polystyrene board 75mm","Spray foam insulation","Reflective foil wrap","Radiant barrier","Insulation clips/fixings","Insulation tape","Underlay nails/clouts"],
"Roof Windows & Skylights":["Skylight - Fixed 600x600","Skylight - Fixed 900x900","Skylight - Opening 600x900","Skylight - Opening 900x1200","Skylight - Dome","Skylight - Pyramid","Skylight - Flat glass","Skylight - Lantern","Roof window - Centre pivot 550x780","Roof window - Centre pivot 780x1180","Roof window - Top hung 780x1180","Roof window flashing kit","Sun tunnel/light pipe","Skylight curb/upstand","Skylight blinds"],
"Roof Accessories & Safety":["Roofing nails 75mm (3in)","Roofing nails 100mm (4in)","Roofing screws - Hex head with washer","Roofing screws - Self-drilling","Silicone sealant - Clear","Silicone sealant - Grey","Silicone sealant - Terracotta","Bituminous paint (5L)","Anti-rust paint (5L)","Roof ladder hook","Roof anchor/safety point","Safety harness - Full body","Safety line/rope","Walkway/platform (roof access)","Lightning rod/air terminal","Lightning conductor tape","Earth rod","Roof ventilator - Turbine","Roof ventilator - Static","Roof ventilator - Powered","Solar panel mounting kit","Bird spikes","Bird netting","Vermin proofing mesh","Snow guard (for tile roofs)"]
};
var ROOF_STATUS=["Not started","Structure erected","Purlins installed","Underlay done","Covering installed","Ridge/hips done","Valleys done","Verges/eaves done","Gutters installed","Insulation done","Inspected","Completed"];

RENDER["roof"]=function(){
var h='<h2>Roofs & Roof Coverings</h2><p style="color:#aaa;font-size:12px">Complete roof system - structure, covering, drainage & accessories</p>';
h+='<div style="display:flex;gap:8px;margin:10px 0"><button class="btn btn-blue btn-sm" onclick="showRoofForm()">+ Add Roof Item</button></div>';
var roof=(D.roof||[]);
if(roof.length===0){h+='<p style="color:#666">No roof items recorded. Add roof structure, covering, and accessories.</p>';}
else{
var cats={};for(var i=0;i<roof.length;i++){var r=roof[i];if(!cats[r.category])cats[r.category]=[];cats[r.category].push(r);}
var ck=Object.keys(cats);
for(var c=0;c<ck.length;c++){var cat=ck[c];var items=cats[cat];
h+='<div class="card"><h4>'+cat+' ('+items.length+' items)</h4><table style="font-size:11px"><tr><th>Item</th><th>Location</th><th>Qty</th><th>Unit</th><th>Status</th></tr>';
for(var i=0;i<items.length;i++){var r=items[i];h+='<tr><td>'+r.name+'</td><td>'+r.location+'</td><td>'+r.qty+'</td><td>'+r.unit+'</td><td><span class="tag '+(r.status==="Completed"||r.status==="Inspected"?"tag-pass":r.status==="Covering installed"||r.status==="Structure erected"?"tag-open":"")+'">'+r.status+'</span></td></tr>';}
h+='</table></div>';
}
}
return h;
};

function showRoofForm(){
var cats="";var ck=Object.keys(ROOF_CATEGORIES);for(var i=0;i<ck.length;i++){cats+='<option value="'+ck[i]+'">'+ck[i]+'</option>';}
var h='<h3>Add Roof Item</h3><label>Date:</label><input type="date" id="_entryDate" value="'+globalDate+'" max="'+today()+'"><label>Category:</label><select id="_rfCat" onchange="loadRoofItems()">'+cats+'</select><label>Item:</label><select id="_rfItem"></select><label>Location/Area:</label><input id="_rfLoc" placeholder="e.g. Main roof, Verandah, Kitchen"><div class="row"><div><label>Quantity:</label><input id="_rfQty" type="number" value="1"></div><div><label>Unit:</label><select id="_rfUnit"><option>Pieces</option><option>Sheets</option><option>Lengths (m)</option><option>m2</option><option>Rolls</option><option>Sets</option><option>Pairs</option><option>Bundles</option></select></div></div><label>Status:</label><select id="_rfStatus">';
for(var i=0;i<ROOF_STATUS.length;i++){h+='<option>'+ROOF_STATUS[i]+'</option>';}
h+='</select><label>Notes:</label><input id="_rfNotes"><button class="btn" onclick="saveRoof()">Save Item</button><button class="btn btn-secondary" onclick="go(\'roof\')">Cancel</button>';
document.getElementById("content").innerHTML=h;loadRoofItems();
}

function loadRoofItems(){var cat=document.getElementById("_rfCat").value;var items=ROOF_CATEGORIES[cat]||[];var h="";for(var i=0;i<items.length;i++){h+='<option>'+items[i]+'</option>';}document.getElementById("_rfItem").innerHTML=h;}

function saveRoof(){
if(!D.roof)D.roof=[];
D.roof.push({id:uid(),date:document.getElementById("_entryDate").value,category:document.getElementById("_rfCat").value,name:document.getElementById("_rfItem").value,location:document.getElementById("_rfLoc").value,qty:document.getElementById("_rfQty").value,unit:document.getElementById("_rfUnit").value,status:document.getElementById("_rfStatus").value,notes:document.getElementById("_rfNotes").value,timestamp:Date.now()});
save();toast("Roof item saved!");go("roof");
}
