// ============ RUNWAY CONSTRUCTION ============
var RUNWAY_CATEGORIES={
"Runway - Earthworks":["Site clearance & grubbing","Topsoil stripping 200mm","Cut to fill - bulk earthworks","Cut to spoil - disposal","Subgrade preparation - scarify & compact","Subgrade compaction - 95% MDD","Subgrade CBR testing - min 15%","Subgrade proof rolling - 50T roller","Subgrade level tolerances +0/-30mm","Subgrade crossfall - 1.5%","Frost protection layer if required","Geotextile separation layer","Ground improvement - lime/cement stabilization","Ground improvement - dynamic compaction","Ground improvement - vibro-compaction"],
"Runway - Sub-base & Base":["Sub-base - crushed stone G45 200mm","Sub-base - crushed stone G60 200mm","Sub-base - crushed stone G80 150mm","Sub-base - cement stabilised 3-5%","Sub-base compaction - 98% MDD","Sub-base CBR testing - min 80%","Sub-base level tolerances +0/-15mm","Base course - graded crushed stone 150mm","Base course - cement stabilised 150mm","Base course - asphalt base 100mm","Base course compaction - 100% MDD","Base course prime coat MC-70","Base course level tolerances +0/-10mm"],
"Runway - Asphalt Paving":["Asphalt binder course AC32 100mm","Asphalt binder course compaction","Asphalt binder level tolerances +0/-8mm","Tack coat between layers","Asphalt wearing course AC14 50mm","Asphalt wearing course - polymer modified","Asphalt wearing course compaction","Asphalt wearing level tolerances +0/-5mm","Asphalt temperature at plant 160-180C","Asphalt temperature at laying >140C","Paver speed 2-3m/min for smoothness","Joint - hot to hot within 1hr","Joint - cold joint cut back and tacked","Joint - longitudinal at lane markings","Surface regularity - 3mm under 3m straightedge","Texture depth - 1.0-1.5mm for skid resistance","Core samples - 1 per 500m2 for thickness","Core samples - density >97%","Air voids - 3-5%","Friction testing - runway surface >0.65mu"],
"Runway - Concrete Paving":["Subgrade/base prepared as per asphalt section","Polyethylene slip sheet if unbonded","Reinforcement - dowel bars at transverse joints","Reinforcement - tie bars at longitudinal joints","Reinforcement - mesh if required","Concrete grade - C40/50 minimum","Concrete slump - 25-40mm (pavement quality)","Concrete placed by slipform paver","Concrete placed by fixed form","Concrete compaction - immersion vibrators","Concrete compaction - surface vibrators","Surface finishing - burlap drag texture","Surface finishing - tining for skid resistance","Surface finishing - grooving for drainage","Curing compound applied within 30 minutes","Curing - wet cure 7 days minimum","Joints - transverse contraction at 5m c/c","Joints - transverse expansion at 30m c/c","Joints - longitudinal at 4.5-5m c/c","Joints - sawn within 24 hours","Joint depth - 1/3 slab thickness","Joint sealant - hot pour, recessed 5mm","Joint sealant - silicone cold pour","Concrete strength - cube tests 3 per 100m3","Concrete strength - 28 day >40MPa","Surface regularity - 3mm under 3m","Texture depth - 1.0mm minimum","Friction testing - >0.65mu"],
"Taxiway Construction":["Taxiway subgrade - same as runway","Taxiway sub-base - same as runway","Taxiway base course - same as runway","Taxiway width - 23m for Code E","Taxiway width - 18m for Code C","Taxiway fillets at intersections - radius 30-45m","Taxiway asphalt or concrete as runway","Taxiway level tolerances as runway","Taxiway shoulder - 7.5m wide","Taxiway shoulder - grass or paved","Taxiway shoulder - able to support occasional loads","Taxiway edge lights - blue, at 60m c/c","Taxiway centerline lights - green at 30m c/c"],
"Apron Construction":["Apron subgrade - CBR >15%","Apron sub-base - 200mm crushed stone","Apron base course - 150mm cement stabilised","Apron surface - concrete 300mm C40/50","Apron surface - asphalt 100mm AC32 + 50mm AC14","Apron slope - 1% away from terminal","Apron slope - 1% towards drainage","Apron fuel hydrant pits - correctly positioned","Apron fuel hydrant pits - level with surface","Apron ground power units - 400Hz","Apron PCA/PCC outlets at each stand","Apron floodlighting - 20 lux minimum","Apron floodlighting - high mast 25-30m","Apron markings - stand numbers","Apron markings - lead-in lines","Apron markings - safety lines","Apron markings - equipment staging areas","Apron drainage - slot drains","Apron drainage - oil/water separator"],
"Runway Drainage":["Surface drainage - crossfall 1.5%","Side drains - concrete lined V-drain","Side drains - trapezoidal lined","Catch basins at 50m c/c","Catch basins - with sump for sediment","Pipe drains - 300mm minimum diameter","Pipe drains - at 30m c/c under runway","Pipe drains - connect to side drains","Pipe drains - rodent proof grates","Subsurface drainage - perforated pipe","Subsurface drainage - at low points","Subsurface drainage - wrapped in geotextile","Outfall structure - headwall","Outfall structure - scour protection","Outfall structure - energy dissipator","Stormwater detention pond if required"],
"Runway Markings & Signs":["Runway centerline - white, 900mm wide","Runway threshold - white stripes","Runway designation - numbers","Runway touchdown zone - stripes","Runway aiming point - white rectangles","Runway edge line - white, 900mm","Runway side stripe - white","Taxiway centerline - yellow, 300mm","Taxiway edge - yellow double line","Taxiway holding position - yellow","Apron safety line - red/white","Marking material - thermoplastic","Marking material - glass beads for reflectivity","Marking thickness - 3mm minimum","Runway distance markers - black/white","Wind direction indicator - illuminated","Wind direction indicator - at each runway end","Mandatory instruction signs - red/white","Mandatory instruction signs - at runway holding","Information signs - yellow/black","Information signs - at taxiway intersections","Signs - frangible mountings","Signs - internally illuminated","Signs - height 900mm above ground"],
"Runway Lighting":["Runway edge lights - white, 60m c/c","Runway edge lights - yellow last 600m","Runway threshold lights - green","Runway end lights - red","Runway centerline lights - white at 15m c/c","Runway centerline lights - alternating red/white last 900m","Runway centerline lights - red last 300m","Touchdown zone lights - white at 30m c/c","Taxiway edge lights - blue at 60m c/c","Taxiway centerline lights - green at 30m c/c","Stop bar lights - red at taxiway holding","Approach lights - centerline 900m","Approach lights - crossbars","PAPI - Precision Approach Path Indicator","PAPI - 4 light units each side","PAPI - set at 3 degree glidepath","Apron floodlights - high mast 25-30m","Apron floodlights - LED 1000W","Wind cone light - illuminated","Obstruction lights - red on tall structures","Lighting control - ALCMS system","Lighting control - individual circuit monitoring","Lighting control - brightness steps (5 levels)","Constant current regulator - CCR","CCR - 6.6A or 20A output","Underground cable - 5kV armoured","Isolation transformer at each light","Earthing - <1 ohm resistance"],
"Runway NAVAIDS":["ILS Localizer - antenna array 300m from runway end","ILS Localizer - clearance checked","ILS Glidepath - 120m from centerline","ILS Glidepath - 3 degree set","ILS Glidepath - clearance checked","ILS DME - co-located with GP","ILS DME - distance accuracy ±30m","ILS inner marker - 1km from threshold","ILS middle marker - 3.5km from threshold","ILS outer marker - 7.2km from threshold","DVOR - Doppler VOR","DVOR - 360 degree check","DVOR - ground plane clear","NDB - Non-Directional Beacon","NDB - antenna tuning unit","ATC radar - primary surveillance","ATC radar - secondary surveillance","ATC radar - coverage verified","MET station - wind speed/direction","MET station - temperature/humidity","MET station - visibility sensor","MET station - ceilometer cloud height","MET station - RVR transmissometer","MET station - barometric pressure"],
"Runway Safety":["Runway strip - 150m each side (Code E)","Runway strip - 75m each side (Code C)","Runway strip - graded, no obstructions","Runway strip - able to support rescue vehicles","Runway end safety area (RESA) - 240m long","RESA - 120m wide","RESA - graded, compacted","RESA - frangible objects only","Runway object free zone - clear","Runway obstacle limitation surfaces - approach","Runway obstacle limitation surfaces - transitional","Runway obstacle limitation surfaces - inner horizontal","Frangible structures only within runway strip","Frangible approach masts","Frangible ILS structures","Perimeter fence - 2.4m high","Perimeter fence - topped with barbed wire","Perimeter fence - security patrol road","Perimeter fence - CCTV at 200m c/c","Access gates - controlled, lockable","Bird control - grass management <150mm","Bird control - bird scaring devices","Bird control - no standing water","Bird control - no waste/food sources","Wildlife management plan in place","Crash rescue access roads - at each end","Crash rescue access roads - all weather","Wind sock - at each runway end","Wind sock - illuminated"]
};
var RUNWAY_STATUS=["Not started","Earthworks","Sub-base","Base","Paving","Markings","Lighting","NAVAIDS","Safety","Commissioned","Completed"];

RENDER["runway"]=function(){
var h='<h2>Runway Construction</h2><p style="color:#aaa;font-size:12px">Runways, Taxiways, Aprons, Lighting & NAVAIDS</p>';
h+='<div style="display:flex;gap:8px;margin:10px 0"><button class="btn btn-blue btn-sm" onclick="showRunwayForm()">+ Add Item</button></div>';
var rw=(D.runway||[]);
if(rw.length===0){h+='<p style="color:#666">No runway items recorded.</p>';}
else{
var cats={};for(var i=0;i<rw.length;i++){var it=rw[i];if(!cats[it.category])cats[it.category]=[];cats[it.category].push(it);}
var ck=Object.keys(cats);
for(var c=0;c<ck.length;c++){var cat=ck[c];var items=cats[cat];
h+='<div class="card"><h4>'+cat+' ('+items.length+')</h4><table style="font-size:10px"><tr><th>Item</th><th>Location</th><th>Qty</th><th>Status</th><th></th></tr>';
for(var i=0;i<items.length;i++){var it=items[i];h+='<tr><td>'+it.name+'</td><td>'+it.location+'</td><td>'+it.qty+' '+it.unit+'</td><td><span class="tag '+(it.status==="Completed"||it.status==="Commissioned"?"tag-pass":"tag-open")+'">'+it.status+'</span></td><td><button class="btn btn-red btn-sm" style="padding:2px 6px;font-size:10px" onclick="delItem(\'runway\',\''+it.id+'\');go(\'runway\')">X</button></td></tr>';}
h+='</table></div>';}
}
return h;
};
function showRunwayForm(){
var cats="";var ck=Object.keys(RUNWAY_CATEGORIES);for(var i=0;i<ck.length;i++){cats+='<option value="'+ck[i]+'">'+ck[i]+'</option>';}
var h='<h3>Add Runway Item</h3><label>Date:</label><input type="date" id="_entryDate" value="'+globalDate+'" max="'+today()+'"><label>Category:</label><select id="_rwCat" onchange="loadRwItems()">'+cats+'</select><label>Item:</label><select id="_rwItem"></select><label>Location:</label><input id="_rwLoc"><div class="row"><div><label>Quantity:</label><input id="_rwQty" type="number" value="1"></div><div><label>Unit:</label><select id="_rwUnit"><option>m</option><option>m2</option><option>m3</option><option>km</option><option>Pieces</option><option>Sets</option></select></div></div><label>Status:</label><select id="_rwStatus">';
for(var i=0;i<RUNWAY_STATUS.length;i++){h+='<option>'+RUNWAY_STATUS[i]+'</option>';}
h+='</select><label>Notes:</label><input id="_rwNotes"><button class="btn" onclick="saveRunway()">Save</button><button class="btn btn-secondary" onclick="go(\'runway\')">Cancel</button>';
document.getElementById("content").innerHTML=h;loadRwItems();
}
function loadRwItems(){var cat=document.getElementById("_rwCat").value;var items=RUNWAY_CATEGORIES[cat]||[];var h="";for(var i=0;i<items.length;i++){h+='<option>'+items[i]+'</option>';}document.getElementById("_rwItem").innerHTML=h;}
function saveRunway(){if(!D.runway)D.runway=[];var d=document.getElementById("_entryDate").value;var name=document.getElementById("_rwItem").value;var loc=document.getElementById("_rwLoc").value;D.runway.push({id:uid(),date:d,category:document.getElementById("_rwCat").value,name:name,location:loc,qty:document.getElementById("_rwQty").value,unit:document.getElementById("_rwUnit").value,status:document.getElementById("_rwStatus").value,notes:document.getElementById("_rwNotes").value,timestamp:Date.now()});save();toast("Saved!");go("runway");}
