// ============ STAIRCASE CONSTRUCTION ============
var STAIRCASE_CATEGORIES={
"Staircase - Setting Out":["Staircase type confirmation - straight/dog-leg/spiral","Staircase position setting out from grid","Staircase width setting out","Staircase going (tread) setting out","Staircase rise (riser) setting out","Staircase headroom 2.1m minimum check","Staircase landing position setting out","Staircase flight length calculation","Staircase pitch angle check 30-38 degrees","Staircase direction of flight confirmation","Staircase handrail position marking","Staircase stringer position marking","Staircase nosing line marking","Staircase winder position (if applicable)","Staircase circular/spiral center point"],
"Staircase - Formwork":["Staircase waist slab soffit formwork","Staircase waist slab side formwork","Staircase riser formwork - timber 25mm","Staircase riser formwork - steel","Staircase tread formwork","Staircase landing formwork","Staircase stringer beam formwork","Staircase support props - acrow under waist","Staircase support props - timber struts","Staircase formwork bracing both directions","Staircase formwork level check","Staircase riser height uniform check","Staircase tread width uniform check","Staircase formwork joints sealed","Staircase mould oil applied","Staircase kicker at first riser","Staircase nosing form/recess formed","Staircase nosings for anti-slip insert","Staircase railing pocket/recess formed","Staircase landing edge beam formwork","Staircase winder formwork (if applicable)","Staircase spiral formwork curved"],
"Staircase - Reinforcement":["Staircase waist slab main bars - bottom","Staircase waist slab distribution bars","Staircase waist slab main bars - top","Staircase waist slab extra bars at supports","Staircase landing slab bottom bars","Staircase landing slab top bars","Staircase landing distribution bars","Staircase stringer beam bottom bars","Staircase stringer beam top bars","Staircase stringer beam stirrups","Staircase cover blocks 20mm minimum","Staircase chairs/spacers for top bars","Staircase bar laps at correct position","Staircase cranked bars at landings","Staircase starter bars from supporting beam","Staircase dowel bars into wall/column","Staircase railing anchor bars cast in","Staircase nosing reinforcement","Staircase winder reinforcement (if applicable)"],
"Staircase - Concreting":["Staircase concrete grade C25/30 minimum","Staircase concrete poured from bottom to top","Staircase concreting continuous pour","Staircase compaction - poker vibrator at waist","Staircase compaction - needle vibrator at risers","Staircase vibration avoiding formwork displacement","Staircase riser face compacted fully","Staircase tread surface screeded level","Staircase tread surface troweled smooth","Staircase nosing edge formed clean","Staircase curing started within 1 hour","Staircase curing - wet hessian for 7 days","Staircase curing - ponding on treads","Staircase formwork removal - risers 24-48hrs","Staircase formwork removal - soffit 14-21 days","Staircase props left in place as per engineer","Staircase cube samples 3 per pour","Staircase 28-day strength >25MPa"],
"Staircase - Finishing":["Staircase screed to treads and risers","Staircase screed falls to drainage if external","Staircase tiling - tread tiles anti-slip R11+","Staircase tiling - riser tiles","Staircase tiling - landing tiles","Staircase nosing - aluminium with anti-slip insert","Staircase nosing - brass","Staircase nosing - tile nosing","Staircase nosing - PVC","Staircase nosing protrusion 15-25mm","Staircase handrail height 900mm above pitch line","Staircase handrail continuous no breaks","Staircase handrail - timber","Staircase handrail - stainless steel","Staircase handrail - mild steel painted","Staircase balusters spacing max 100mm","Staircase balusters fixed securely","Staircase balusters - vertical bars","Staircase balusters - decorative panels","Staircase landing balustrade height 1100mm","Staircase wall handrail for accessibility","Staircase step marking - contrasting nosing","Staircase step lighting - LED strip under nosing","Staircase step lighting - recessed in riser","Staircase painting - stringer/wall","Staircase varnishing - timber handrail"],
"Staircase - Types":["Straight staircase - single flight","Straight staircase - with landing","Dog-leg staircase","Open-well staircase","Quarter-turn staircase","Half-turn staircase","Three-quarter turn","Spiral staircase - central column","Helical staircase - curved","Cantilever staircase - treads from wall","Floating staircase - open riser","Alternating tread staircase","Winder staircase","Ladder staircase - steep","Fire escape staircase - external steel","Monumental staircase - feature","Escalator - if applicable"]
};
var STAIRCASE_STATUS=["Not started","Setting out","Formwork","Reinforcement","Concreting","Curing","Stripping","Finishing","Completed"];

RENDER["staircase"]=function(){
var h='<h2>Staircase Construction</h2><p style="color:#aaa;font-size:12px">From Setting Out to Finishing</p>';
h+='<div style="display:flex;gap:8px;margin:10px 0"><button class="btn btn-blue btn-sm" onclick="showStaircaseForm()">+ Add Item</button></div>';
var st=(D.staircase||[]);
if(st.length===0){h+='<p style="color:#666">No staircase items recorded.</p>';}
else{
var cats={};for(var i=0;i<st.length;i++){var it=st[i];if(!cats[it.category])cats[it.category]=[];cats[it.category].push(it);}
var ck=Object.keys(cats);
for(var c=0;c<ck.length;c++){var cat=ck[c];var items=cats[cat];
h+='<div class="card"><h4>'+cat+' ('+items.length+')</h4><table style="font-size:10px"><tr><th>Item</th><th>Location</th><th>Qty</th><th>Status</th><th></th></tr>';
for(var i=0;i<items.length;i++){var it=items[i];h+='<tr><td>'+it.name+'</td><td>'+it.location+'</td><td>'+it.qty+' '+it.unit+'</td><td><span class="tag '+(it.status==="Completed"?"tag-pass":"tag-open")+'">'+it.status+'</span></td><td><button class="btn btn-red btn-sm" style="padding:2px 6px;font-size:10px" onclick="delItem(\'staircase\',\''+it.id+'\');go(\'staircase\')">X</button></td></tr>';}
h+='</table></div>';}
}
return h;
};
function showStaircaseForm(){
var cats="";var ck=Object.keys(STAIRCASE_CATEGORIES);for(var i=0;i<ck.length;i++){cats+='<option value="'+ck[i]+'">'+ck[i]+'</option>';}
var h='<h3>Add Staircase Item</h3><label>Date:</label><input type="date" id="_entryDate" value="'+globalDate+'" max="'+today()+'"><label>Category:</label><select id="_scCat" onchange="loadScItems()">'+cats+'</select><label>Item:</label><select id="_scItem"></select><label>Location:</label><input id="_scLoc"><div class="row"><div><label>Quantity:</label><input id="_scQty" type="number" value="1"></div><div><label>Unit:</label><select id="_scUnit"><option>m</option><option>m2</option><option>Pieces</option><option>Flights</option><option>Sets</option></select></div></div><label>Status:</label><select id="_scStatus">';
for(var i=0;i<STAIRCASE_STATUS.length;i++){h+='<option>'+STAIRCASE_STATUS[i]+'</option>';}
h+='</select><label>Notes:</label><input id="_scNotes"><button class="btn" onclick="saveStaircase()">Save</button><button class="btn btn-secondary" onclick="go(\'staircase\')">Cancel</button>';
document.getElementById("content").innerHTML=h;loadScItems();
}
function loadScItems(){var cat=document.getElementById("_scCat").value;var items=STAIRCASE_CATEGORIES[cat]||[];var h="";for(var i=0;i<items.length;i++){h+='<option>'+items[i]+'</option>';}document.getElementById("_scItem").innerHTML=h;}
function saveStaircase(){if(!D.staircase)D.staircase=[];var d=document.getElementById("_entryDate").value;var name=document.getElementById("_scItem").value;var loc=document.getElementById("_scLoc").value;D.staircase.push({id:uid(),date:d,category:document.getElementById("_scCat").value,name:name,location:loc,qty:document.getElementById("_scQty").value,unit:document.getElementById("_scUnit").value,status:document.getElementById("_scStatus").value,notes:document.getElementById("_scNotes").value,timestamp:Date.now()});save();toast("Saved!");go("staircase");}
