var STAIRCASE_CATEGORIES={
"Straight Flight":["Setting out - position and direction","Setting out - total rise measurement","Setting out - total going measurement","Setting out - number of risers calculated","Setting out - number of treads = risers - 1","Setting out - width clear minimum 900mm","Setting out - FFL and landing levels marked","Formwork - waist soffit on props at 1m c/c","Formwork - soffit level checked","Reinforcement - waist bottom bars placed","Reinforcement - distribution bars at 200mm c/c","Reinforcement - top bars at supports","Reinforcement - cover blocks 20mm","Reinforcement - chairs under top bars","Formwork - side shutters fixed after rebar","Formwork - riser boards 25mm fixed after rebar","Formwork - tread boards if required","Formwork - joints sealed","Formwork - mould oil applied","Formwork - plumb and level check","Concreting - C25/30 minimum","Concreting - pour bottom to top","Concreting - compact waist with poker","Concreting - compact risers","Concreting - screed treads level","Concreting - trowel risers smooth","Curing - wet hessian 7 days","Striking - risers 48 hours","Striking - soffit 14-21 days","Finishing - tread anti-slip","Finishing - nosing 15-25mm projection","Finishing - handrail 900mm height","Finishing - balusters 100mm max spacing"],
"Dog-Leg":["Setting out - two flights with landing","Setting out - half landing position","Setting out - landing width = stair width","Setting out - direction change 180 degrees","Formwork - first flight soffit","Formwork - first flight soffit level","Reinforcement - first flight bottom bars","Reinforcement - first flight distribution bars","Reinforcement - first flight top bars at supports","Formwork - first flight side shutters","Formwork - first flight riser boards","Formwork - landing soffit","Reinforcement - landing bottom bars","Reinforcement - landing top bars","Reinforcement - continuity bars through landing","Formwork - landing side shutters","Formwork - second flight soffit","Reinforcement - second flight bottom bars","Reinforcement - second flight distribution bars","Reinforcement - second flight top bars at supports","Formwork - second flight side shutters","Formwork - second flight riser boards","Concreting - first flight + landing + second flight together","Concreting - construction joint at mid-landing only","Curing - 7 days all flights","Striking - risers 48 hours","Striking - soffit 21 days","Finishing - landing level","Finishing - handrail continuous through landing","Finishing - newel post at turn","Finishing - balustrade around landing"],
"Open-Well":["Setting out - open well in center","Setting out - well size 600x600mm min","Setting out - flights around well","Formwork - first flight soffit","Reinforcement - first flight bars","Formwork - first flight side shutters","Formwork - first flight risers","Formwork - landing soffit","Reinforcement - landing bars","Formwork - landing side shutters","Formwork - second flight soffit","Reinforcement - second flight bars","Formwork - second flight side shutters","Formwork - second flight risers","Formwork - well edge beam formwork","Reinforcement - well edge beams","Concreting - flights sequential","Concreting - landings","Curing - 7 days","Striking - as per engineer","Finishing - well balustrade","Finishing - well lighting","Finishing - continuous handrail","Finishing - anti-climb protection"],
"Spiral":["Setting out - center point established","Setting out - overall diameter","Setting out - tread width at center 240mm min","Setting out - tread width at outer edge","Setting out - headroom 2.1m min","Formwork - central column formwork","Reinforcement - central column bars","Concreting - central column first","Formwork - tread soffit supports radial","Reinforcement - radial bars each tread","Reinforcement - spiral ties","Formwork - tread side shutters","Formwork - riser formers curved","Concreting - each tread individually bottom to top","Concreting - compact carefully","Curing - 7 days","Striking - 21 days","Finishing - center column finish","Finishing - treads anti-slip","Finishing - handrail spiral continuous","Finishing - balusters radial"],
"Helical":["Setting out - helical geometry","Setting out - start and end positions","Setting out - rise per tread","Setting out - total rotation","Formwork - curved soffit","Reinforcement - curved bars","Reinforcement - helical ties","Formwork - curved side shutters","Formwork - individually marked formers","Concreting - continuous pour","Concreting - careful compaction","Curing - 14 days","Striking - 28 days","Finishing - premium finish","Finishing - lighting integrated","Finishing - handrail follows helix"],
"Cantilever":["Setting out - tread positions on wall","Setting out - embedment depth 150mm","Setting out - tread projection","Formwork - individual tread soffit","Reinforcement - tread bars into wall","Reinforcement - dowels from wall","Formwork - tread side shutters","Formwork - tread front riser","Concreting - each tread separately C30/37","Curing - 7 days per tread","Striking - 7 days per tread","Finishing - no visible support","Finishing - tread anti-slip","Finishing - wall handrail","Finishing - load test if specified"],
"Floating":["Setting out - stringer position","Setting out - tread positions","Steel stringer fabrication","Steel stringer installation","Steel stringer level checked","Tread fixing - hidden brackets","Tread fixing - no visible fixings","Tread level checked each","Tread spacing uniform","Handrail - glass balustrade","Handrail - steel wire","Load test if required"],
"Fire Escape":["Setting out - external location","Setting out - landing at each floor","Setting out - width 900mm min","Steel stringers fabrication","Steel stringers installation","Steel landings fabrication","Steel landings installation","Support brackets to wall","Treads - steel grating","Treads - anti-slip","Handrail - 1100mm height","Handrail - continuous","Balustrade - vertical bars","Self-closing gate at ground","Fire rating - protected route","Signage - fire escape","Lighting - emergency"],
"Winder":["Setting out - winder positions","Setting out - 3-4 winders per quarter turn","Setting out - tread narrow end 50mm min","Formwork - each winder soffit","Reinforcement - each winder bars","Reinforcement - continuity with straight flights","Formwork - winder side shutters","Formwork - winder risers","Concreting - winders with flights","Curing - 7 days","Striking - 21 days","Finishing - nosing marking","Finishing - anti-slip","Finishing - handrail follows winder"],
"Concrete Precast":["Factory - mould preparation","Factory - reinforcement cage","Factory - inserts for connections","Factory - lifting loops","Factory - concrete C40/50","Factory - steam curing","Factory - demoulding","Factory - quality check","Delivery - lifting points checked","Delivery - no damage","Erection - bearing pads","Erection - alignment","Erection - grouting joints","Erection - tie bars","Erection - temporary props","Finishing - joint sealant","Finishing - level check","Finishing - handrail fixing"],
"Steel Fabricated":["Fabrication - stringer cutting","Fabrication - tread plate cutting","Fabrication - welding","Fabrication - drilling fixings","Fabrication - primer coat","Fabrication - finish coat","Fabrication - quality check","Delivery - no distortion","Erection - stringer installation","Erection - site welding","Erection - bolting connections","Erection - tread installation","Erection - level check","Finishing - touch-up paint","Finishing - handrail","Finishing - balustrade"]
};
var STAIRCASE_STATUS=["Not started","Setting out","Formwork","Reinforcement","Side shutters & risers","Concreting","Curing","Striking","Finishing","Completed"];
RENDER["staircase"]=function(){
var h='<h2>Staircase Construction</h2><p style="color:#aaa;font-size:12px">Each stair type with correct sequence: soffit → rebar → sides → risers → pour</p>';
h+='<div style="display:flex;gap:8px;margin:10px 0"><button class="btn btn-blue btn-sm" onclick="showStaircaseForm()">+ Add Item</button></div>';
var st=(D.staircase||[]);
if(st.length===0){h+='<p style="color:#666">No staircase items recorded.</p>';}
else{
var cats={};for(var i=0;i<st.length;i++){var it=st[i];if(!cats[it.category])cats[it.category]=[];cats[it.category].push(it);}
var ck=Object.keys(cats);
for(var c=0;c<ck.length;c++){var cat=ck[c];var items=cats[cat];
h+='<div class="card"><h4>'+cat+' ('+items.length+')</h4><table style="font-size:10px"><tr><th>Item</th><th>Location</th><th>Qty</th><th>Status</th><th></th></tr>';
for(var i=0;i<items.length;i++){var it=items[i];h+='<tr><td>'+it.name+'</td><td>'+it.location+'</td><td>'+it.qty+' '+it.unit+'</td><td><span class="tag '+(it.status==="Completed"?"tag-pass":"tag-open")+'">'+it.status+'</span></td><td><button class="btn btn-red btn-sm" style="padding:2px 6px;font-size:10px" onclick="delItem(\'staircase\',\''+it.id+'\');go(\'staircase\')">X</button></td></tr>';}
h+='</table></div>';}
}
return h;
};
function showStaircaseForm(){
var cats="";var ck=Object.keys(STAIRCASE_CATEGORIES);for(var i=0;i<ck.length;i++){cats+='<option value="'+ck[i]+'">'+ck[i]+'</option>';}
var h='<h3>Add Staircase Item</h3><label>Date:</label><input type="date" id="_entryDate" value="'+globalDate+'" max="'+today()+'"><label>Staircase Type:</label><select id="_scCat" onchange="loadScItems()">'+cats+'</select><label>Item:</label><select id="_scItem"></select><label>Location:</label><input id="_scLoc"><div class="row"><div><label>Quantity:</label><input id="_scQty" type="number" value="1"></div><div><label>Unit:</label><select id="_scUnit"><option>m</option><option>m2</option><option>Flights</option><option>Pieces</option><option>Sets</option></select></div></div><label>Status:</label><select id="_scStatus">';
for(var i=0;i<STAIRCASE_STATUS.length;i++){h+='<option>'+STAIRCASE_STATUS[i]+'</option>';}
h+='</select><label>Notes:</label><input id="_scNotes"><button class="btn" onclick="saveStaircase()">Save</button><button class="btn btn-secondary" onclick="go(\'staircase\')">Cancel</button>';
document.getElementById("content").innerHTML=h;loadScItems();
}
function loadScItems(){var cat=document.getElementById("_scCat").value;var items=STAIRCASE_CATEGORIES[cat]||[];var h="";for(var i=0;i<items.length;i++){h+='<option>'+items[i]+'</option>';}document.getElementById("_scItem").innerHTML=h;}
function saveStaircase(){if(!D.staircase)D.staircase=[];var d=document.getElementById("_entryDate").value;var name=document.getElementById("_scItem").value;var loc=document.getElementById("_scLoc").value;D.staircase.push({id:uid(),date:d,category:document.getElementById("_scCat").value,name:name,location:loc,qty:document.getElementById("_scQty").value,unit:document.getElementById("_scUnit").value,status:document.getElementById("_scStatus").value,notes:document.getElementById("_scNotes").value,timestamp:Date.now()});save();toast("Saved!");go("staircase");}
