var UPPERFLOOR_CATEGORIES={
"RC Solid Slab":["Setting out - FFL and slab thickness","Setting out - beam positions if downstand","Formwork - soffit plywood 18mm","Formwork - props at 1.2m c/c","Formwork - level ±5mm","Reinforcement - bottom bars main span","Reinforcement - distribution bars","Reinforcement - top bars at supports","Reinforcement - cover blocks 25mm","Concreting - C25/30 min","Concreting - pump or skip","Concreting - poker vibrator","Concreting - level to FFL","Curing - ponding 7 days","Striking - soffit 14-21 days","Backpropping below","Finishing - screed if required"],
"RC Ribbed Slab":["Setting out - rib positions","Setting out - rib width 100-150mm","Setting out - rib spacing 400-600mm","Formwork - soffit level","Formwork - rib formers timber","Formwork - hollow block or void formers between ribs","Reinforcement - rib bottom bars","Reinforcement - rib links/stirrups","Reinforcement - topping mesh A142","Reinforcement - distribution bars in topping","Concreting - ribs first then topping","Concreting - C25/30","Concreting - compaction in ribs","Concreting - topping 50-75mm","Curing - 7 days","Striking - ribs 14 days","Striking - soffit 21 days"],
"RC Waffle Slab":["Setting out - waffle grid positions","Setting out - waffle size 600x600 or 900x900","Formwork - table form system","Formwork - waffle moulds plastic","Formwork - waffle moulds steel","Formwork - level ±3mm","Reinforcement - ribs both directions","Reinforcement - rib links","Reinforcement - topping mesh","Reinforcement - solid band at columns","Concreting - C30/37","Concreting - compaction around moulds","Concreting - topping 75mm min","Curing - 7 days min","Striking - moulds released","Striking - table forms lowered","Backpropping - 2 floors below"],
"Precast Hollow Core":["Setting out - bearing lines on walls","Setting out - bearing width 100mm min","Delivery - check units for damage","Delivery - check lifting points","Erection - crane capacity","Erection - lifting beam/spreader","Erection - first unit placed","Erection - subsequent units aligned","Grouting - bedding mortar under units","Grouting - key joints grouted","Tie bars at joints","In-situ topping 50mm min","Topping mesh A142","Topping level to FFL","Topping cured 7 days","Services holes cut before concreting","Holes not through prestressing strands"],
"Precast Beam & Block":["Setting out - beam positions","Setting out - bearing on walls","Beam placement - concrete beams","Beam placement - steel beams","Beam bearing 100mm min","Beam level checked","Block placement between beams","Block density 1350kg/m3 max","Block type - hollow clay/concrete","Blocks laid tight between beams","No blocks resting on edges only","In-situ topping 50mm min","Topping reinforcement A142","Topping falls for drainage where required","Topping cured 7 days"],
"Composite Steel Deck":["Setting out - deck span direction","Setting out - bearing on beams 50mm","Deck - profile 60mm deep minimum","Deck - gauge 0.9mm min","Deck - fixed by shot pins","Deck - side laps stitched","Deck - end laps 100mm","Shear studs welded through deck","Shear stud spacing per design","Shear stud pull-out test","Edge trim/closure installed","Mesh A193 placed","Mesh chaired 25mm","Concrete C25/30 min","Concrete placed evenly","Concrete depth checked at low points","Vibration - poker at supports","Surface power float","Temporary props if span >3m","No overloading during construction"],
"Post-Tensioned Slab":["Setting out - tendon profiles","Setting out - anchorage positions","Formwork - soffit level ±3mm","Formwork - edges and openings","Tendon installation - ducts","Tendon installation - profiles at supports","Tendon installation - profiles at midspan","Tendon anchorage - fixed end","Tendon anchorage - stressing end","Bursting reinforcement at anchors","Shear reinforcement at anchors","Concrete C35/45 minimum","Concrete placement avoids ducts","Concrete compaction around anchors","Stressing after 25MPa","Stressing jack calibrated","Stressing sequence as per design","Elongation measured and recorded","Force within ±5%","Wedge seating checked","No slippage during lock-off","Tendon cutting and capping","Anchor grouting","Tendon grouting - cement grout","Tendon grouting - no voids","Striking after full stressing"],
"Timber Joist Floor":["Setting out - joist positions at 400mm c/c","Joist size and grade checked","Joist span checked against tables","Joist bearing 75mm min on masonry","Joist hangers - correct type and size","Joist hangers - fixed with nails/screws","Rim board/header joist installed","Blocking at midspan","Blocking at supports","Double joists under partitions","Trimmer joists around openings","Doubled joists at stair opening","Decking - T&G boards 25mm","Decking - chipboard 22mm","Decking - plywood 18mm","Decking - screwed not nailed","Decking - adhesive at joints","Expansion gap 10mm perimeter","Acoustic insulation between joists","Fire stopping between joists","Ventilation to floor void","DPC under joists on masonry","Deflection check <span/360"],
"Bubble Deck Slab":["Setting out - bubble positions","Setting out - bubble size 180-450mm diameter","Setting out - slab thickness","Bubble deck - prefabricated cages delivered","Bubble deck - cages placed on formwork","Bubble deck - cages aligned","Bubble deck - no bubbles floating","Additional reinforcement at columns","Additional reinforcement at openings","Concrete C30/37 minimum","Concrete placed carefully - no bubble displacement","Compaction - poker around bubbles","Surface level to FFL","Curing - 7 days minimum","Striking - as per engineer","Weight saving verified - check deflection"]
};
var UPPERFLOOR_STATUS=["Not started","Setting out","Formwork/Deck","Reinforcement","Concreting","Curing/Stressing","Stripping","Finishing","Completed"];
RENDER["upperfloor"]=function(){
var h='<h2>Upper Floor Construction</h2><p style="color:#aaa;font-size:12px">Each floor type tracked separately</p>';
h+='<div style="display:flex;gap:8px;margin:10px 0"><button class="btn btn-blue btn-sm" onclick="showUpperfloorForm()">+ Add Item</button></div>';
var uf=(D.upperfloor||[]);
if(uf.length===0){h+='<p style="color:#666">No upper floor items recorded.</p>';}
else{
var cats={};for(var i=0;i<uf.length;i++){var it=uf[i];if(!cats[it.category])cats[it.category]=[];cats[it.category].push(it);}
var ck=Object.keys(cats);
for(var c=0;c<ck.length;c++){var cat=ck[c];var items=cats[cat];
h+='<div class="card"><h4>'+cat+' ('+items.length+')</h4><table style="font-size:10px"><tr><th>Item</th><th>Location</th><th>Qty</th><th>Status</th><th></th></tr>';
for(var i=0;i<items.length;i++){var it=items[i];h+='<tr><td>'+it.name+'</td><td>'+it.location+'</td><td>'+it.qty+' '+it.unit+'</td><td><span class="tag '+(it.status==="Completed"?"tag-pass":"tag-open")+'">'+it.status+'</span></td><td><button class="btn btn-red btn-sm" style="padding:2px 6px;font-size:10px" onclick="delItem(\'upperfloor\',\''+it.id+'\');go(\'upperfloor\')">X</button></td></tr>';}
h+='</table></div>';}
}
return h;
};
function showUpperfloorForm(){
var cats="";var ck=Object.keys(UPPERFLOOR_CATEGORIES);for(var i=0;i<ck.length;i++){cats+='<option value="'+ck[i]+'">'+ck[i]+'</option>';}
var h='<h3>Add Upper Floor Item</h3><label>Date:</label><input type="date" id="_entryDate" value="'+globalDate+'" max="'+today()+'"><label>Floor Type:</label><select id="_ufCat" onchange="loadUfItems()">'+cats+'</select><label>Item:</label><select id="_ufItem"></select><label>Location:</label><input id="_ufLoc"><div class="row"><div><label>Quantity:</label><input id="_ufQty" type="number" value="1"></div><div><label>Unit:</label><select id="_ufUnit"><option>m2</option><option>m3</option><option>m</option><option>Pieces</option><option>Sets</option></select></div></div><label>Status:</label><select id="_ufStatus">';
for(var i=0;i<UPPERFLOOR_STATUS.length;i++){h+='<option>'+UPPERFLOOR_STATUS[i]+'</option>';}
h+='</select><label>Notes:</label><input id="_ufNotes"><button class="btn" onclick="saveUpperfloor()">Save</button><button class="btn btn-secondary" onclick="go(\'upperfloor\')">Cancel</button>';
document.getElementById("content").innerHTML=h;loadUfItems();
}
function loadUfItems(){var cat=document.getElementById("_ufCat").value;var items=UPPERFLOOR_CATEGORIES[cat]||[];var h="";for(var i=0;i<items.length;i++){h+='<option>'+items[i]+'</option>';}document.getElementById("_ufItem").innerHTML=h;}
function saveUpperfloor(){if(!D.upperfloor)D.upperfloor=[];var d=document.getElementById("_entryDate").value;var name=document.getElementById("_ufItem").value;var loc=document.getElementById("_ufLoc").value;D.upperfloor.push({id:uid(),date:d,category:document.getElementById("_ufCat").value,name:name,location:loc,qty:document.getElementById("_ufQty").value,unit:document.getElementById("_ufUnit").value,status:document.getElementById("_ufStatus").value,notes:document.getElementById("_ufNotes").value,timestamp:Date.now()});save();toast("Saved!");go("upperfloor");}
